# -*- Doc -*-
= AVR32 Toolchain Builder =
James Snyder <jbsnyder@fanplastic.org>
v1.0, Sat Apr 16 20:40:49 CDT 2011

== AVR32 Toolchain Builder ==

This is a early implementation of a Makefile for an AVR32 toolchain
builder for Mac OS X & Linux. Currently more work is required before
this is generally useful, at which time a fuller README will be
fleshed out there.

Note: If you have previously built a toolchain of another version, out
of the same builder directory, make sure to do the following first
before building with newer sources:

----
make clean
----

=== Requirements (OS X) ===

You will need to have GCC, make and binutils on your machine to
compile all of this.  You can get all of these on Mac OS X, by just
installing the Apple
link:http://developer.apple.com/technologies/tools/[Developer Tools].
You should be able to download free versions of 3.x from the ADC
website, install from the OS X install disc that came with your
machine, or purchase XCode 4 for US$4.99 from the App Store (free if
you're a member of the Mac or iOS developer program).

You will also need gmp, mpfr and mpc first.  I recommend installing
these from link:https://github.com/mxcl/homebrew[homebrew] for now.
I'll add these to the Makefile once I have a consistent configuration
that can be used for both Linux & OS X.

With homebrew you can install those dependencies like this:
----
brew install mpfr gmp libmpc
----

Additionally, you may find that you need more recent versions of
autoconf and automake for this build to run correctly, I'm currently
investigating options on this and will update instructions and the
Makefile when a fairly streamlined solution is found.


=== Requirements (Ubuntu) ===

These instructions should now also work on Ubuntu Linux, provided the
following packages have been installed prior to attempting the build:

----
sudo apt-get install curl flex bison libgmp3-dev libmpfr-dev autoconf build-essential libncurses5-dev libmpc-dev texinfo
----

=== Main Build Instructions ===

Next build the toolchain:

----
make install-cross
----

his should build the compiler, newlib, gdb, etc.. and install them all
into a directory called arm-cs-tools in your home directory. If you
want to install to another location, feel free to change the export
lines and to adjust the definitions at the top of the Makefile.

Keep in mind that the Makefile does install at the end of each build.

Once you’re done, you’ll likely want to add the path where the
compiler was installed to to your .bash_profile, .zshrc, etc..:

----
export PATH=$HOME/avr32-tools/bin:$PATH
----

=== Special Thanks ===

Special thanks to Rob Emanuele for the basis of this Makefile:
http://elua-development.2368040.n2.nabble.com/Building-GCC-for-Cortex-td2421927.html
